name: Pull Request Merge
on:
  push:
    branches:
      - main

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "My pull request title"
          body: "My pull request body"
          branch: "dev"
          labels: release-sync
          assignees: luizhv
          auto-merge: merge