on:
  push:
    branches:
      - main

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "dev"
          pr_title: "Pulling ${{ github.ref }} into dev"
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}