name: Release sync
run-name: Syncing release to dev environments
on:
  push:
    branches:
      - main

jobs:
  sync-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create staging pull request
        id: staging
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "staging"
          pr_title: "Sync ${{ github.ref_name }} into staging"
          pr_allow_empty: true
          pr_body: "**Automated pull request**"
          pr_assignee: luizhv
          pr_label: release-sync
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable Auto Merge
        if: ${{ steps.staging.outputs.pr_number }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.staging.outputs.pr_number }}
          merge-method: merge
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create dev pull request
        id: dev
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "dev"
          pr_title: "Sync ${{ github.ref_name }} into dev"
          pr_allow_empty: true
          pr_body: "**Automated pull request**"
          pr_assignee: luizhv
          pr_label: release-sync
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable Auto Merge
        if: ${{ steps.dev.outputs.pr_number }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.dev.outputs.pr_number }}
          merge-method: merge